# Generated by Django 4.2.4 on 2023-08-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_app', '0002_remove_plate_ingredient_id_plate_ingredient_id'),
        ('journal_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal_entry',
            name='plate_id',
        ),
        migrations.AddField(
            model_name='journal_entry',
            name='plate_id',
            field=models.ManyToManyField(related_name='plates', to='plate_app.plate'),
        ),
    ]
