# Generated by Django 4.2.4 on 2023-08-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0004_remove_journal_entry_plate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
