# Generated by Django 4.2.4 on 2023-08-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plate_app', '0002_remove_plate_ingredient_id_plate_ingredient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='unitName',
            new_name='unit_name',
        ),
    ]
