# Generated by Django 4.2.4 on 2023-08-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_app', '0004_remove_plate_ingredient_id_ingredient_plate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
