# Generated by Django 4.2.4 on 2023-08-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0003_remove_journal_entry_plate_id_journal_entry_plate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal_entry',
            name='plate_id',
        ),
    ]
