# Generated by Django 4.2.4 on 2023-08-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='ingredient_id',
        ),
        migrations.AddField(
            model_name='plate',
            name='ingredient_id',
            field=models.ManyToManyField(related_name='ingredients', to='plate_app.ingredient'),
        ),
    ]
