# Generated by Django 4.2.4 on 2023-08-17 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0005_alter_journal_entry_created_at'),
        ('plate_app', '0005_alter_plate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='journal_entry_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='journal_app.journal_entry'),
        ),
    ]
