# Generated by Django 4.2.4 on 2023-08-18 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plate_app', '0006_alter_plate_journal_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='plate_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='plate_app.plate'),
        ),
    ]
