# Generated by Django 4.2.3 on 2023-08-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_app', '0007_alter_ingredient_plate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount_consumed',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
