# Generated by Django 4.2.3 on 2023-08-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_app', '0008_ingredient_amount_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='percentDailyValue',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
