# Generated by Django 4.2.3 on 2023-08-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plate_app', '0009_nutrient_percentdailyvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='percentDailyValue',
        ),
    ]
