# Generated by Django 4.2.3 on 2023-08-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_app', '0010_remove_nutrient_percentdailyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='percentDailyValue',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
