# Generated by Django 4.2.3 on 2023-08-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate_app', '0011_nutrient_percentdailyvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='percentDailyValue',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
