# Generated by Django 4.2.3 on 2023-08-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
