# Generated by Django 4.2.3 on 2023-08-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
